### ISSUE TITLE
I think tracking is erroring out, if it is not able to find for some frame

### ISSUE THREAD

**Issue by m-ali-awan** [logtd/ComfyUI-InstanceDiffusion#6]
Hi 
I am able to see generated video with tracking showing in comfy, but it highlights the node: `Instance Diffusion Tracking Prompt`, and I think for some frame tracking info misses
```


Traceback (most recent call last):
  File "/mnt/efs/fs1/GenerativeAI/ComfyUI-Stuff/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/efs/fs1/GenerativeAI/ComfyUI-Stuff/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/efs/fs1/GenerativeAI/ComfyUI-Stuff/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt/efs/fs1/GenerativeAI/ComfyUI-Stuff/ComfyUI/custom_nodes/ComfyUI-InstanceDiffusion/nodes/instance_diffusion_tracking_prompt_node.py", line 71, in append
    negative_positions = self._get_position_conds(
  File "/mnt/efs/fs1/GenerativeAI/ComfyUI-Stuff/ComfyUI/custom_nodes/ComfyUI-InstanceDiffusion/nodes/instance_diffusion_tracking_prompt_node.py", line 35, in _get_position_conds
    tracking[class_id][tracker_id]}
KeyError: 1
```

Is there any way, where we can make sure that we have tracking results for all frames, if for some frame it misses we can use aggregate between following and previous frame results...

**Comment by m-ali-awan** [comment]
Sorry , it seems this is not the issue..

```
"52.person": "(((The Mad Hatter, purple suit, purple top hot, red hair)))",
"53.person": "(((a white rabbit wearing a suit, white bunny ears)))",
"54.person": "((((Alice in Wonderland, blue dress, white apron, blonde))))",
"55.person": "((((the Queen of Hearts, red and black dress, crown))))",
```
By changing person numbering to what is detected ,solves that problem..

**Comment by yuntianhe2014** [comment]
这个是因为你 画面中没有那多人人，只有1个人，你却写了多个
